# How Can Nonprofits Use AI to Personalize Something To Increase Donor Retention

In [1]:
import pandas as pd
import matplotlib.pyplot as pyplot
import numpy as np
import seaborn as sns
import scipy as sp

In [3]:
normalized_df = pd.read_csv('../ai_survey_normalized_clustering_data.csv')
survey_df = pd.read_csv('../ai_survey_results_2024_n=930.csv')

In [4]:
normalized_df.head()

,Unnamed: 0,nonprofit,org_years,regionality,org_small_med_large,global_north_south_int,collects_data,tech_person,merl_person,cloud_storage,...,[W] Generat,[W] Interpret,[W] Organi,[W] Predict,[W] Translat,[W] Other,[W] We don't know yet!,cluster3,cluster2,ai_want_2+
0,0,1.0,0.560000,0.25,1.0,0.0,1.0,0.0,0.0,1.0,...,0,0,1,1,0,0,0,1,1,1
1,1,1.0,0.046667,0.25,0.0,0.0,1.0,0.0,0.0,1.0,...,1,1,1,1,1,1,0,0,0,1
2,2,1.0,0.226667,0.25,0.0,0.0,1.0,1.0,0.0,1.0,...,0,1,0,0,1,0,0,-1,0,1
3,3,1.0,0.166667,0.50,0.0,0.0,1.0,1.0,1.0,1.0,...,0,1,1,1,0,0,0,1,1,1
4,4,1.0,0.053333,0.50,0.0,0.0,1.0,0.0,0.0,1.0,...,1,1,1,1,1,0,0,0,0,1

In [5]:
survey_df.head()

,Unnamed: 0,source,Start time,nonprofit,non_org_type,role,person_org_years,org_size,org_years,continent,...,global_north_south_int,org_size_int,hubs_rural_urban_int,af_region_int,india_rural_urban_int,collab_feasibility_raw,person_ai_comfort_raw,org_years_raw,person_org_years_raw,cluster3
0,0,The big one,2024-03-07 11:03:50,1.0,NaN,Fundraiser,0.066667,31-60,0.560000,North America,...,0.0,5.0,NaN,NaN,NaN,7.0,7.0,84.0,4.0,1
1,1,The big one,2024-03-07 11:03:03,1.0,NaN,Leader,0.116667,0-5,0.046667,North America,...,0.0,0.0,NaN,NaN,NaN,4.0,5.0,7.0,7.0,0
2,2,The big one,2024-03-07 11:05:30,1.0,NaN,Leader,0.016667,6-15,0.226667,North America,...,0.0,1.0,NaN,NaN,NaN,3.0,10.0,34.0,1.0,-1
3,3,The big one,2024-03-07 11:05:30,1.0,NaN,Comms,0.133333,6-15,0.166667,North America,...,0.0,1.0,NaN,NaN,NaN,8.0,10.0,25.0,8.0,1
4,4,The big one,2024-03-07 11:07:06,1.0,NaN,Leader,0.133333,0-5,0.053333,North America,...,0.0,0.0,NaN,NaN,NaN,4.0,0.0,8.0,8.0,0